apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-sample-e2e
  namespace: kubernetes-sample
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: kubernetes-sample-e2e
    spec:
      restartPolicy: Never
      containers:
        - name: e2e
          image: kubernetes-sample-e2e
          command: ["npm", "run", "test"]
          imagePullPolicy: IfNotPresent
